// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk-XNaDaIjTS_zBKJMtAPVJxuVsfR3BhY',
    appId: '1:809512268949:web:c12dd1c379d4e87ce6579c',
    messagingSenderId: '809512268949',
    projectId: 'zawag3-e6346',
    authDomain: 'zawag3-e6346.firebaseapp.com',
    storageBucket: 'zawag3-e6346.appspot.com',
    measurementId: 'G-JKWT94FRRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUkw6IKwx7htUl1W2MSaoI4C2Y33gEC4Y',
    appId: '1:809512268949:android:3801f866a0dc8e79e6579c',
    messagingSenderId: '809512268949',
    projectId: 'zawag3-e6346',
    storageBucket: 'zawag3-e6346.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8faMBowNQpcMFNwFyNoEWcbDHBppswLA',
    appId: '1:809512268949:ios:9449e9f98513249ee6579c',
    messagingSenderId: '809512268949',
    projectId: 'zawag3-e6346',
    storageBucket: 'zawag3-e6346.appspot.com',
    iosBundleId: 'com.example.effa',
  );

}